POST http://localhost:5000/api/url/shorten
Content-Type: application/json

{
    "longUrl": "https://www.amazon.com/Samsung-Galaxy-Unlocked-Smartphone-Renewed/dp/B07VPRRQBD/ref=lp_18637575011_1_1?srs=18637575011&ie=UTF8&qid=1571320019&sr=8-1"
}